# Generated by Django 4.2.3 on 2023-07-22 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_recommender', '0002_alter_book_publication_date_alter_book_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'managed': False},
        ),
    ]
