# Generated by Django 4.2.3 on 2023-07-22 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_recommender', '0004_alter_book_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
