# Generated by Django 4.2.3 on 2023-07-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_recommender', '0005_alter_book_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
